my_blog/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login', views.user_login, name="login"),
    path('register', views.user_register, name="register"),
    path('logout', views.user_logout, name="logout"),
    path('profile', views.user_profile, name='profile'),
    path('profile_edit', views.profile_edit, name='profile_edit'),
    path('password_change', views.password_change, name='password_change'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('accounts.urls')),
    path('', include('posts.urls')),
    path('comments/', include('comments.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'  # this is the namespace of the app

urlpatterns = [
    path('', views.post_list, name='base'),
    path('post/<slug:slug>/', views.post_details, name='post'),
    path('post_create/', views.post_create, name='post_create'),
    path('edit/<slug:slug>/', views.post_edit, name='edit'),
    path('delete/<slug:slug>/', views.post_delete, name='delete'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact')
]

my_blog/posts/models.py
import random

from datetime import datetime, timedelta
from markdown_deux import markdown

from django.conf import settings
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType

from comments.models import Comment
from .utils import get_read_time, random_string_generator

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Note! : Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(publish__lte=timezone.now())


def upload_location(post, file_name):
    return "{}/{}".format(post.id, file_name)


class Post(models.Model):
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    title           = models.CharField(max_length=128)
    slug            = models.SlugField()
    width_field     = models.IntegerField(default=0)
    height_field    = models.IntegerField(default=0)
    content         = models.TextField() 
    publish         = models.DateField(auto_now=False, auto_now_add=False, default=timezone.now())
    updated         = models.DateTimeField(auto_now=True, auto_now_add=False)
    time_stamp      = models.DateTimeField(auto_now=False, auto_now_add=True)
    time_now        = datetime.now()
    image           = models.ImageField(
                upload_to=upload_location, 
                null=True, 
                blank=True, 
                width_field="width_field", 
                height_field="height_field",
    )

    read_time = models.IntegerField(default=0)
    # read_time = get_read_time(content)

    objects = PostManager()
    # to return post title as object name, instead "Post object"
    def __str__(self):
        return self.title
        
    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    def get_absolute_url(self):
        # return "/posts/%s/" %(self.slug) 
        # ^ it's not fully dynamic, it works with {{ post.get_absolute_url }} inside the post.html
        return reverse("posts:post", kwargs={'slug': self.slug})  # to reverse and make even more dynamic

    def edit_url(self):
        return reverse("posts:edit", kwargs={'slug': self.slug})
    
    def delete_url(self):
        return reverse("posts:delete", kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-time_stamp', '-updated']

    # simple slug generator

    def save(self, *args, **kwargs):
        # slugify title
        # self.slug = slugify("{obj.product_name}-{obj.id}".format(obj=self))
        size = random.randint(5, 9)
        self.slug = slugify("{slug}-{rand_str}".format(slug=self.title, rand_str=random_string_generator(size=size)))
        # read time auto-generated
        self.read_time = get_read_time(self.content)
        
        super(Post, self).save(*args, **kwargs)

my_blog/posts/forms.py
from django import forms
from django.utils import timezone

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    # publish = forms.DateField(widget=forms.SelectDateWidget, initial=timezone.now())
    class Meta:
        model = Post
        fields = [
            'title', 'image', 'content'
        ]

my_blog/posts/views.py
from urllib.parse import quote_plus

from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q

from .utils import get_read_time
from .models import Post
from .forms import PostForm
from comments.forms import CommentForm
from comments.models import Comment


def post_create(request):
    
    if not request.user.is_authenticated: # or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)  # request.POST => for form validation 

    if form.is_valid() and request.method == "POST":
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, 'Post Created Successfully')  
        return HttpResponseRedirect(instance.get_absolute_url())
    
    context = {'form': form}
    return render(request, 'post_create.html', context)

def post_edit(request, slug=None):
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)  # request.POST => for form validation 
    
    if not request.user.is_authenticated or not request.user.is_superuser:
        raise Http404
    
    if form.is_valid() and request.method == "POST":
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Updates saved!')
        return HttpResponseRedirect(instance.get_absolute_url()) 
    else:
        messages.error(request, 'Not saved')
    
    context = {
        'title': post.title,
        'post': post,
        'form': form,
    }
    return render(request, 'post_create.html', context=context)

@login_required
def post_delete(request, slug=None):
    
    if not request.user.is_authenticated or not request.user.is_superuser:
        raise Http404
        
    post = get_object_or_404(Post, slug=slug)
    post.delete()
    messages.success(request, 'Post Successfully deleted')

    return redirect('posts:base')


def post_list(request):
    post_list = Post.objects.active()  # .filter(draft=False).filter(publish__lte=timezone.now())  # .order_by("-time_stamp")
    if request.user.is_superuser or request.user.is_staff:
        post_list = Post.objects.all()

    query = request.GET.get('q')
    if query:
        post_list = Post.objects.all()
        post_list = post_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query)
            # Q(user__first_name__icontains=query) |
            # Q(user__last_name__icontains=query)
        ).distinct()

    paginator = Paginator(post_list, 5)  # Show 25 posts per page
    # page_request_var = 'page'  # to make it mor dynamic for pagination
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    create_url = reverse('posts:post_create')
    
    context = {
        'post_list': post_list,
        'posts': posts,
        # 'page_request_var': page_request_var,
        'create': create_url,
    }

    return render(request, 'base.html', context)


def post_details(request, slug=None):
    post_list = Post.objects.active()
    post = get_object_or_404(Post, slug=slug)
    # if post.publish > timezone.now().date() or post.draft:
    #     if not request.user.is_authenticated or not request.user.is_superuser:
    #         raise Http404
    
    share_string = quote_plus(post.content)
    
    initial_data = {
        "content_type": post.get_content_type,
        "object_id": post.id,
    }
    
    # post read time 
    read_time = get_read_time(post.content)
    # print(type(read_time))
    
    form = CommentForm(request.POST or None, initial=initial_data)
    
    if form.is_valid() and request.user.is_authenticated:
        c_type = form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get('content')
        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None
            
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        
        new_comment, created = Comment.objects.get_or_create(
            user = request.user,
            content_type = content_type,
            object_id = obj_id,
            content = content_data,
            parent = parent_obj,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = post.comments # Comment.objects.filter_by_instance(post)  # without @property

    context = {
        'post': post,
        'share_string': share_string,
        'comments': comments,
        'comment_form': form,
        'read_time': read_time,
    }
    return render(request, 'post.html', context=context)

# About, Contact sections

def about(request):
    context = {}
    return render(request, 'about.html', context)


def contact(request):
    context = {}
    return render(request, 'contact.html', context)



''' 
# this for checking if the user is authenticated or not
if request.user.is_authenticated:
        context = {'title': 'this text for authenticated user'}
        return render(request, 'index.html', context=context)
    else:
        context = {'title': 'this text for non authenticated users'}
        return render(request, 'index.html', context=context)
    
'''

my_blog/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- bootstrap 4 -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <title>About</title>
    </head>
    <body style="padding: 30px;">
        <p>this about page.... in progress</p>
        <a class="btn btn-primary" href="{% url 'posts:base' %}">Back To Home</a>
    </body>
</html>

my_blog/templates/comment_thread.html
{% extends 'base.html' %}

{% load static %}
{% load markdown_deux_tags %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ comment.content | truncatechars:12 }} | {{ block.super }}
{% endblock head_title %}

{% block content %}

    <section class="comment_thread" style="margin-top: 150px;padding: 10px 0;min-height: 800px;">
        <div class="container">
            <div class="row">
                <div class="comment_section offset-sm-1 col-sm-8">

                    <!-- Single Comment thread -->
                    <div class="media mb-4">
                        <hr>
                        <img class="d-flex mr-3 rounded user_image" src="{{ comment.user.profile.image.url }}" alt="user-image">
                        <div class="media-body">
                            <h5 class="mt-0">{{ comment.user }}:</h5> 
                            <div class="content">
                                <p class="lead">{{ comment.content | markdown }}</p>
                            </div>
                            <!-- links -->
                            <div class="links">
                                <!-- <a href="#" class="badge badge-primary" id="like">like</a>&nbsp;&nbsp; -->
                                
                                {% if user.is_authenticated %}
                                <a href="#" class="badge badge-primary" id="reply_comment">Reply</a>&nbsp;&nbsp;
                                {% endif %}
                                
                                {% if user.is_authenticated  and request.user == comment.user or request.user.is_superuser %}
                                <a href="{{ comment.delete_url }}" class="badge badge-danger">Delete</a>&nbsp;&nbsp;
                                {% endif %}
                                    
                                <i class="fa fa-angle-right"></i>&nbsp;
                                <small>{{ comment.time_stamp }}</small>
                                &nbsp;
                                {% if comment.children.count > 0 %}
                                <span class="badge badge-warning">replies: {{ comment.children.count }}</span>
                                {% endif %}
                                    
                            </div>

                            <!-- reply form -->
                            
                            {% if user.is_authenticated %}
                            
                            <form method="POST" action="" id="reply_form">
                                {% csrf_token %}
                                {{ comment_form | crispy }}
                                <input type="hidden" name="parent_id" value='{{ comment.id }}'>
                                <input type="submit" class="btn btn-primary" value="Post Reply">
                            </form><!-- reply_form -->
                            
                            {% else %}
                            <p>You must login to post a reply</p>
                            <a class="btn btn-primary" href="{% url 'accounts:login' %}" style="margin-bottom: 15px;">Login</a>
                            <br>
                            {% endif %}
                                
                            <hr>

                            <!-- reply content -->

                            {% for child_comment in comment.children %}
                                <div class="media mt-4 replay_cont">
                                    <img class="d-flex mr-3 rounded" src="http://placehold.it/35x35" alt="">
                                    <div class="media-body">
                                        <h5 class="mt-0">{{ child_comment.user }}</h5> 
                                        <div class="content">
                                            <p class="lead">{{ child_comment.content | markdown }}</p>
                                        </div>
                                        <div class="links">
                                            <!-- <a href="#" class="badge badge-primary" id="like">like</a>&nbsp;&nbsp; -->
                                            <!-- {% if user.is_authenticated  and request.user == child_comment.user or user.is_superuser %}
                                            <a href="{{ comment.delete_url }}" class="badge badge-danger">Delete</a>&nbsp;&nbsp;
                                            {% endif %} -->
                                            <i class="fa fa-angle-right"></i>&nbsp;
                                            <small>{{ child_comment.time_stamp }}</small>
                                        </div>

                                    </div>
                                </div>
                            {% endfor %}

                        </div><!-- media-body -->
                    </div><!-- media -->

                </div><!-- comment_section -->  
            </div><!-- row -->
        </div><!-- container -->
    </section>

{% endblock content %}

my_blog/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- bootstrap 4 -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <title>Contact</title>
    </head>
    <body style="padding: 30px;">
        <p>this Contact page.... in progress</p>
        <a class="btn btn-primary" href="{% url 'posts:base' %}">Back To Home</a>
    </body>
</html>

my_blog/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block head_title %}
    {{ title }}
{% endblock head_title %}


{% block navbar %}

{% endblock navbar %}

    {% block content %}
        <section id="forms">
            <div class="container">
                <div class="row">
                    
                    <div class="login-box">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    {{ message }} <i class="fas fa-arrow-down"></i>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <div class="lb-header text-center">
                            <label class="active" id="login-box-link">Login</label>
                        </div><!-- header -->

                        <!--<div class="social-login pl-5">
                            <a href="#">
                                <i class="fab fa-facebook-f fa-lg"></i> Login by facebook
                            </a>
                            <a href="#">
                                <i class="fab fa-google fa-lg"></i> login by Google
                            </a>
                        </div> social logins -->

                        <form class="email-login text-center" method="POST" action="">

                            {% csrf_token %}
                            {{ login_form | crispy }}
                            
                            <input type="submit" value="Login" class="btn btn-primary" style="width:200px">
                            <br>
                            <br>
                            <!-- <div class="u-form-group">  
                                <a href="#" class="forgot-password">Forgot password?</a>
                            </div> -->
                            
                            <div class="u-form-group">
                                Not a member?, <a href="{% url 'accounts:register' %}" style="color: #09f">Register Now</a>
                            </div>
                        </form><!-- form login -->

                    </div><!-- login-box -->

                </div><!-- row -->
            </div><!-- container -->
        </section>
    {% endblock content %}
    

{% block footer %}
    
{% endblock footer %}
    

my_blog/templates/password_change.html
{% extends 'base.html' %}

{% load static %}
{% load markdown_deux_tags %}
{% load crispy_forms_tags %}


{% block head_title %}
    Change Password
{% endblock head_title %}


{% block content %}


    <section class="profile password_change">
        
        <div class="container">
            <div class="content">
                <div class="card">
                    <h2 class="card-header text-white bg-dark"><i class="fas fa-user"></i> {{ user.username }}</h2>
                    
                    <div class="profile_pic">
                        <img class="img-fluid" src="{{ user.profile.image.url }}">
                    </div><!-- profile_pic -->
                    <hr>
                    <div class="card-body">
                        <h2 class=""><i class="fas fa-user"></i>&nbsp; Change Password for: {{ user.username }}</h2><br>

                        <form method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form | crispy }}

                            <input type='submit' value="Update Password" class="btn btn-primary">&nbsp;
                            <a class="btn btn-secondary" href="{% url 'accounts:profile' %}">Cancel</a>
                        </form>
                    </div>
                
                </div><!-- card -->

            </div><!-- content -->
        </div><!-- container -->
    </section>    


{% endblock content %}
    

{% block footer %}
    
{% endblock footer %}

my_blog/templates/profile.html
{% extends 'base.html' %}

{% load static %}
{% load markdown_deux_tags %}
{% load crispy_forms_tags %}


{% block head_title %}
    {{ user.username }}
{% endblock head_title %}


{% block content %}

    <section class="profile">
        
        <div class="container">
            <div class="content">
                <div class="card">
                    <h2 class="card-header text-white bg-dark"><i class="fas fa-user"></i> {{ user.username }}</h2>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="row">
                        
                        <div class="profile_pic col-md-5">
                            
                            {% if user.profile.image.url %}
                            <img class="img-fluid" src="{{ user.profile.image.url }}">
                            {% else %}
                            <img class="img-fluid" src="{% static 'img/no-photo.png' %}">
                            {% endif %}
                                
                        </div><!-- profile_pic -->
                        
                        <div class="card-body col-md-7">
                            <h5 class="card-title"><i class="fas fa-info-circle"></i>&nbsp; Your Info</h5>
                            <hr>
                            <p class="card-text"><span>Username:</span> {{ user.username }}</p>
                            <p class="card-text"><span>Full Name:</span> {{ user.first_name }} {{ user.last_name }}</p>
                            <p class="card-text"><span>Email:</span> {{ user.email }}</p>
                            <p class="card-text"><span>Job Title:</span> {{ user.profile.job_title }}</p>
                            <p class="card-text"><span>Bio:</span> {{ user.profile.bio }}</p>
                            <p class="card-text"><span>Password:</span> 
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                                <i class="fas fa-circle"></i>
                            </p>
                            <a href="{% url 'accounts:profile_edit' %}" class="btn btn-primary">Edit Info</a>&nbsp;
                            <a href="{% url 'accounts:password_change' %}" class="btn btn-primary">Change Password</a>
                        </div>
                    </div><!-- row -->
                    
                    
                    {% if request.user.is_authenticated %}
                        <hr>
                        <h2 style="margin-left: 20px;"><i class="fas fa-file-alt"></i> Posts By You</h2>
                        <hr>
                        <br>    

                        {% for post in posts %}
                            <div class="bd-callout bd-callout-success">
                                <h4>{{ post.title }}</h4>
                                <p>{{ post.content | truncatechars_html:120 }}</p>
                                <br>
                                <a href="{{ post.get_absolute_url }}" class="btn btn-primary" target="_blank">Read More &rarr;</a>
                                <div class="card-footer text-muted" style="margin-top: 8px;">
                                    <i class="fa fa-calendar-alt"></i>&nbsp;<span class="date">{{ post.time_stamp }}</span>&nbsp;
                                    <!-- <span class="views_n">| <i class="fa fa-eye"></i> 235</span>&nbsp;&nbsp; -->
                                    <span class="time_reading">
                                        | <i class="far fa-clock"></i>&nbsp;Read Time: {% if post.read_time < 1 %} less than 1 Minute {% else %} {{ post.read_time }} Minute {% endif %}
                                    </span>
                                    {% if post.draft %}
                                        <span class="btn btn-warning">Draft</span>
                                    {% endif %}
                                </div><!-- card-footer -->
                            </div>
                        {% endfor %}    
                    
                    {% endif %}

                </div>

            </div><!-- content -->
        </div><!-- container -->
    </section>    
{% endblock content %}
    



{% block footer %}
    
{% endblock footer %}
    

<!-- 

  -->

my_blog/templates/profile_edit.html
{% extends 'base.html' %}

{% load static %}
{% load markdown_deux_tags %}
{% load crispy_forms_tags %}


{% block head_title %}
    Edit profile
{% endblock head_title %}


{% block content %}


    <section class="profile profile_edit">
        
        <div class="container">
            <div class="content">
                <div class="card">
                    <h2 class="card-header text-white bg-dark"><i class="fas fa-user"></i> {{ user.username }}</h2>
                    
                    <div class="profile_pic">
                        <img class="img-fluid" src="{{ user.profile.image.url }}">
                    </div><!-- profile_pic -->
                    <hr>
                    <div class="card-body">
                        <form method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ u_form | crispy }}
                            {{ p_form | crispy }}
                            
                            <input type='submit' value="Update" class="btn btn-primary">&nbsp;
                            <a class="btn btn-secondary" href="{% url 'accounts:profile' %}">Cancel</a>
                        </form>
                    </div>
                
                </div><!-- card -->

            </div><!-- content -->
        </div><!-- container -->
    </section>    


{% endblock content %}
    

{% block footer %}
    
{% endblock footer %}

my_blog/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block head_title %}
    {{ title }}
{% endblock head_title %}


{% block navbar %}

{% endblock navbar %}

    {% block content %}
        <section id="forms">
            <div class="container">
                <div class="row">

                    <div class="signup-box">
                        <div class="lb-header text-center">
                            <label class="active" id="login-box-link">Register New Account</label>
                        </div><!-- header -->

                        <!--<div class="social-login pl-5">
                            <a href="#">
                                <i class="fab fa-facebook-f fa-lg"></i>&nbsp; Register by facebook
                            </a>
                            <a href="#">
                                <i class="fab fa-google fa-lg"></i>&nbsp; Register by Google
                            </a>
                        </div><!-- social logins -->

                        <form class="email-signup text-center" method="POST" action="">

                            {% csrf_token %}
                            {{ register_form | crispy }}
                            
                            <input type="submit" value="Register" class="btn btn-primary" style="width:200px">
                            <br>
                            <br>
                            
                            <div class="u-form-group">
                                Already a member?, <a href="{% url 'accounts:login' %}" style="color: #09f">Login</a>
                            </div>
                        </form><!-- form login -->

                    </div><!-- login-box -->

                </div><!-- row -->
            </div><!-- container -->
        </section>
    {% endblock content %}
    

{% block footer %}
    
{% endblock footer %}
    